name: bundle-chart

on:
  push:
    branches:
      - main

jobs:
  bundle-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: hotbird.docker.nexus.macslabs.de/docker/ci-helm-image:fc6e855
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: package
        id: package
        run: |
          mkdir dist
          helm package --dependency-update ./bitnami_charts/bitnami/external-dns --destination dist
          ls -al dist
      - name: Push to registry
        id: push
        run: |
          for file in "./dist"/*; do
            if [ -f "$file" ]; then
              echo "uploading: $file"
              curl -u $USER:$PASS $REGISTRY --upload-file $file
            fi
          done          